version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  e2e:
    jobs:
      steps:
        - attach_workspace:
          at: ~/
        - cypress/run:
            name: Cypress E2E tests
            cypress-command: 'npx cypress run --record'
